test_that("invalid 'object", {
  data("mtcars")
  n <- nrow(mtcars)
  optcfg <- el_control(tol = 1e-08, th = 1e+10)
  fit <- el_lm(mpg ~ hp, mtcars, control = optcfg)
  expect_error(eld(fit, control = list(maxit = 20L)))
  eld <- eld(fit)
  pdf(NULL)
  plot(eld)
  expect_length(eld@eld, n)
  lhs <- matrix(c(1, -1), nrow = 1)
  fit2 <- elt(fit, lhs = lhs)
  expect_error(eld(mtcars))
  fit@data <- matrix(NA_real_, nrow = 0L, ncol = 0L)
  expect_error(eld(fit))
  expect_error(eld(fit2))
})
