test_that("invalid control parameters", {
  skip_on_os("windows", arch = "i386")
  expect_error(melt_control(eee = 10))
  expect_error(melt_control(maxit = NA))
  expect_error(melt_control(maxit = 0.1))
  expect_error(melt_control(maxit_l = NA))
  expect_error(melt_control(maxit_l = 0.1))
  expect_error(melt_control(tol = Inf))
  expect_error(melt_control(tol = -1))
  expect_error(melt_control(tol_l = Inf))
  expect_error(melt_control(tol_l = -1))
  expect_error(melt_control(th = Inf))
  expect_error(melt_control(th = -10))
})
