test_that("probabilities add up to 1", {
  skip_on_os("windows", arch = "i386")
  x <- rnorm(10)
  par <- (max(x) + min(x)) / 2
  optcfg <- list(maxi = 10)
  expect_warning(el_mean(par, x, control = optcfg))
  optcfg <- list(maxit = NA)
  expect_error(el_mean(par, x, control = optcfg))
  optcfg <- list(maxit = 0.1)
  expect_error(el_mean(par, x, control = optcfg))
  optcfg <- list(tol = Inf)
  expect_error(el_mean(par, x, control = optcfg))
  optcfg <- list(tol = -1)
  expect_error(el_mean(par, x, control = optcfg))
  optcfg <- list(th = Inf)
  expect_error(el_mean(par, x, control = optcfg))
  optcfg <- list(th = -10)
  expect_error(el_mean(par, x, control = optcfg))
})
