test_that("invalid control parameters", {
  skip_on_os("windows", arch = "i386")
  expect_error(control_el(eee = 10))
  expect_error(control_el(maxit = NA))
  expect_error(control_el(maxit = 0.1))
  expect_error(control_el(maxit_l = NA))
  expect_error(control_el(maxit_l = 0.1))
  expect_error(control_el(tol = Inf))
  expect_error(control_el(tol = -1))
  expect_error(control_el(tol_l = Inf))
  expect_error(control_el(tol_l = -1))
  expect_error(control_el(th = Inf))
  expect_error(control_el(th = -10))
  expect_error(control_el(nthreads = c(10, 20)))
  expect_warning(control_el(nthreads = 0))
  expect_warning(control_el(nthreads = .Machine$integer.max))
})
