// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// elMeancpp
List elMeancpp(arma::rowvec theta, arma::mat x, int maxit, double abstol);
RcppExport SEXP _bayesELcpp_elMeancpp(SEXP thetaSEXP, SEXP xSEXP, SEXP maxitSEXP, SEXP abstolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    rcpp_result_gen = Rcpp::wrap(elMeancpp(theta, x, maxit, abstol));
    return rcpp_result_gen;
END_RCPP
}
// test2sample2_cpp
List test2sample2_cpp(NumericVector x, NumericVector y, double b, double alpha, unsigned int maxit, double abstol);
RcppExport SEXP _bayesELcpp_test2sample2_cpp(SEXP xSEXP, SEXP ySEXP, SEXP bSEXP, SEXP alphaSEXP, SEXP maxitSEXP, SEXP abstolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    rcpp_result_gen = Rcpp::wrap(test2sample2_cpp(x, y, b, alpha, maxit, abstol));
    return rcpp_result_gen;
END_RCPP
}
// test2sample777_cpp
List test2sample777_cpp(NumericVector x, NumericVector y, double b, double alpha, unsigned int maxit, double abstol);
RcppExport SEXP _bayesELcpp_test2sample777_cpp(SEXP xSEXP, SEXP ySEXP, SEXP bSEXP, SEXP alphaSEXP, SEXP maxitSEXP, SEXP abstolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    rcpp_result_gen = Rcpp::wrap(test2sample777_cpp(x, y, b, alpha, maxit, abstol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bayesELcpp_elMeancpp", (DL_FUNC) &_bayesELcpp_elMeancpp, 4},
    {"_bayesELcpp_test2sample2_cpp", (DL_FUNC) &_bayesELcpp_test2sample2_cpp, 6},
    {"_bayesELcpp_test2sample777_cpp", (DL_FUNC) &_bayesELcpp_test2sample777_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_bayesELcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
