# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute empirical likelihood for mean
#'
#' Compute empirical likelihood for mean
#'
#' @param theta a vector of parameters to be tested.
#' @param x a matrix or vector of data. Each row is an observation vector.
#' @param abstol an optional value for the absolute convergence tolerance. Defaults to 1e-8.
#' @param maxit an optional value for the maximum number of iterations. Defaults to 50.
#' @export
elMeancpp <- function(theta, x, maxit = 100L, abstol = 1e-8) {
    .Call(`_bayesELcpp_elMeancpp`, theta, x, maxit, abstol)
}

#' Two sample test for equal mean
#'
#' Two sample test for equal mean
#'
#' @param x a vector of data for one  group.
#' @param y a vector of data for the other  group.
#' @param b a momentum parameter for minimization. Defaults to .1.
#' @param maxit an optional value for the maximum number of iterations. Defaults to 1000.
#' @param abstol an optional value for the absolute convergence tolerance. Defaults to 1e-8.
#'
#' @examples
#' x <- rnorm(100)
#' y <- rnorm(100)
#' test2sample2(x, y)
#'
#' @export
test2sample_cpp <- function(x, y, b = .9, maxit = 1000L, abstol = 1e-8) {
    .Call(`_bayesELcpp_test2sample_cpp`, x, y, b, maxit, abstol)
}

#' Two sample test for equal mean
#'
#' Two sample test for equal mean
#'
#' @param x a vector of data for one  group.
#' @param y a vector of data for the other  group.
#' @param b a momentum parameter for minimization. Defaults to .1.
#' @param alpha an optional step size. Defaults to 1.
#' @param maxit an optional value for the maximum number of iterations. Defaults to 1000.
#' @param abstol an optional value for the absolute convergence tolerance. Defaults to 1e-8.
#'
#' @examples
#' x <- rnorm(100)
#' y <- rnorm(100)
#' test2sample2_cpp(x, y)
#'
#' @export
test2sample2_cpp <- function(x, y, b = .9, alpha = 1, maxit = 1000L, abstol = 1e-8) {
    .Call(`_bayesELcpp_test2sample2_cpp`, x, y, b, alpha, maxit, abstol)
}

#' Two sample test for equal mean
#'
#' Two sample test for equal mean
#'
#' @param x a vector of data for one  group.
#' @param y a vector of data for the other  group.
#' @param b a momentum parameter for minimization. Defaults to .1.
#' @param alpha an optional step size. Defaults to 1.
#' @param maxit an optional value for the maximum number of iterations. Defaults to 1000.
#' @param abstol an optional value for the absolute convergence tolerance. Defaults to 1e-8.
#'
#' @examples
#' x <- rnorm(100)
#' y <- rnorm(100)
#' test2sample777_cpp(x, y)
#'
#' @export
test2sample777_cpp <- function(x, y, b = .9, alpha = 1, maxit = 1000L, abstol = 1e-8) {
    .Call(`_bayesELcpp_test2sample777_cpp`, x, y, b, alpha, maxit, abstol)
}

