# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ELtest <- function(x, c, lhs, rhs, threshold, maxit = 1e4L, abstol = 1e-8) {
    .Call(`_melt_ELtest`, x, c, lhs, rhs, threshold, maxit, abstol)
}

EL_lm <- function(data, intercept, maxit, abstol) {
    .Call(`_melt_EL_lm`, data, intercept, maxit, abstol)
}

EL_mean <- function(par, x, maxit, abstol) {
    .Call(`_melt_EL_mean`, par, x, maxit, abstol)
}

EL_confint <- function(x, type, init, cutoff, idx, maxit, abstol) {
    .Call(`_melt_EL_confint`, x, type, init, cutoff, idx, maxit, abstol)
}

pairwise <- function(x, c, control = 0L, k = 1L, level = 0.05, interval = TRUE, method = "AMC", B = 1e4L, nthread = 1L, progress = TRUE, threshold = 50, maxit = 1e4L, abstol = 1e-8) {
    .Call(`_melt_pairwise`, x, c, control, k, level, interval, method, B, nthread, progress, threshold, maxit, abstol)
}

